spring:
  application:
    name: terawarehouse-service-discovery
  profiles:
    active:
    - ${spring.profiles.active}
    
server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: eureka