spring:
  application:
    name: terawarehouse-service-discovery
  profiles:
    active:
    - ${spring.profiles.active}
    
server:
  port: 8761

eureka:
  environment: ${spring.profiles.active}
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    appname: eureka